#!/usr/bin/env sh

# Only allow commits on main
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$CURRENT_BRANCH" != "main" ]; then
    echo "Error: Commits are only allowed on the 'main' branch"
    echo "       Current branch: $CURRENT_BRANCH"
    exit 1
fi

FORBIDDEN_FILES="hosts/ThinkPadX13/networkig/firewall/default.nix"
STAGED_FILES=$(git diff --cached --name-only)

for s_file in $STAGED_FILES; do
    for f_file in $FORBIDDEN_FILES; do
        if [ "$s_file" = "$f_file" ]; then
            echo "Error: You cannot commit '$f_file'"
            echo "       Unstage this file from git staging"
            exit 1
        fi
    done
done
