{
  pkgs,
  zen-browser-pkg,
}:
let
  frompkgs = with pkgs; [
    babashka
    bitwarden-cli
    brightnessctl
    cargo
    clang-tools
    clojure
    clojure-lsp
    cmake
    copilot-language-server
    deno
    discord
    dockerfile-language-server-nodejs
    efm-langserver
    eslint
    fd
    gcc
    ghq
    git-credential-manager
    gnumake
    gopls
    graphviz
    hyprcursor
    hyprland-qtutils
    jdt-language-server
    killall
    leiningen
    libnotify
    lua
    lua-language-server
    markdown-oxide
    networkmanagerapplet
    nixd
    nixfmt-rfc-style
    nodePackages.bash-language-server
    nodejs_22
    pinentry-curses
    playerctl
    pyright
    (python3.withPackages (ps: with ps; [ numpy pandas matplotlib ]))
    rpi-imager
    ruff
    rust-analyzer
    rustc
    rustfmt
    slack
    soundwireserver
    spotify
    svelte-language-server
    texlab
    texliveFull
    thunderbird
    traceroute
    trash-cli
    typescript-language-server
    unzip
    vim-language-server
    vscode-langservers-extracted
    whois
    wl-clipboard
    yaml-language-server
    zip
    zoom-us
  ];
  zen-browser = [
    zen-browser-pkg
  ];
in
[
  {
    home.packages = frompkgs ++ zen-browser;
  }
]
