{
  pkgs,
}:
let
  frompkgs = with pkgs; [
    basedpyright
    clojure-lsp
    copilot-language-server
    devenv
    dockerfile-language-server
    enchant
    eslint
    fd
    gh
    git-credential-manager
    github-copilot-cli
    google-java-format
    hadolint
    hunspellDicts.en_US-large
    jdt-language-server
    killall
    lua-language-server
    marksman
    nixd
    nixfmt
    nodePackages.bash-language-server
    nodejs_24
    prettier
    ruff
    rust-analyzer
    rustfmt
    shellcheck
    shfmt
    sqls
    stylua
    svelte-language-server
    taplo
    tenv
    terraform-ls
    tflint
    trash-cli
    typescript-language-server
    unzip
    vim-language-server
    vscode-langservers-extracted
    yaml-language-server
  ];
in
[
  {
    home.packages = frompkgs;
  }
]
